# SPDX-PackageName: gel-python
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright Gel Data Inc. and the contributors.


import enum

from gel._internal._polyfills import StrEnum


class Token(StrEnum):
    ADDASSIGN = "+="
    AMPER = "&"
    ARROW = "->"
    ASSIGN = ":="
    AT = "@"
    CIRCUMFLEX = "^"
    COLON = ":"
    COMMA = ""
    DISTINCTFROM = "?!="
    DOT = "."
    DOTBW = ".<"
    DOUBLECOLON = "::"
    DOUBLEPLUS = "++"
    DOUBLEQMARK = "??"
    DOUBLESLASH = "//"
    DOUBLESTAR = "**"
    EQUALS = "="
    GREATEREQ = ">="
    LANGBRACKET = "<"
    LBRACE = "{"
    LBRACKET = "["
    LESSEQ = "<="
    LPAREN = "("
    MINUS = "-"
    NOTDISTINCTFROM = "?="
    NOTEQ = "!="
    PERCENT = "%"
    PIPE = "|"
    PLUS = "+"
    RANGBRACKET = ">"
    RBRACE = "}"
    RBRACKET = "]"
    REMASSIGN = "-="
    RPAREN = ")"
    SCONST = "SCONST"
    SEMICOLON = ";"
    SLASH = "/"
    STAR = "*"

    BCONST = "BCONST"
    FCONST = "FCONST"
    ICONST = "ICONST"
    NFCONST = "NFCONST"
    NICONST = "NICONST"
    IDENT = "IDENT"

    # Reserved keywords
    __SOURCE__ = "__SOURCE__"
    __SUBJECT__ = "__SUBJECT__"
    __TYPE__ = "__TYPE__"
    __STD__ = "__STD__"
    __EDGEDBSYS__ = "__EDGEDBSYS__"
    __EDGEDBTPL__ = "__EDGEDBTPL__"
    __NEW__ = "__NEW__"
    __OLD__ = "__OLD__"
    __SPECIFIED__ = "__SPECIFIED__"
    __DEFAULT__ = "__DEFAULT__"
    ADMINISTER = "ADMINISTER"
    ALTER = "ALTER"
    ANALYZE = "ANALYZE"
    AND = "AND"
    ANYTUPLE = "ANYTUPLE"
    ANYTYPE = "ANYTYPE"
    ANYOBJECT = "ANYOBJECT"
    BY = "BY"
    COMMIT = "COMMIT"
    CONFIGURE = "CONFIGURE"
    CREATE = "CREATE"
    DELETE = "DELETE"
    DESCRIBE = "DESCRIBE"
    DETACHED = "DETACHED"
    DISTINCT = "DISTINCT"
    DO = "DO"
    DROP = "DROP"
    ELSE = "ELSE"
    EXISTS = "EXISTS"
    EXTENDING = "EXTENDING"
    FALSE = "FALSE"
    FILTER = "FILTER"
    FOR = "FOR"
    GLOBAL = "GLOBAL"
    GROUP = "GROUP"
    IF = "IF"
    ILIKE = "ILIKE"
    IN = "IN"
    INSERT = "INSERT"
    INTROSPECT = "INTROSPECT"
    IS = "IS"
    LIKE = "LIKE"
    LIMIT = "LIMIT"
    MODULE = "MODULE"
    NOT = "NOT"
    OFFSET = "OFFSET"
    OPTIONAL = "OPTIONAL"
    OR = "OR"
    ROLLBACK = "ROLLBACK"
    SELECT = "SELECT"
    SET = "SET"
    SINGLE = "SINGLE"
    START = "START"
    TRUE = "TRUE"
    TYPEOF = "TYPEOF"
    UPDATE = "UPDATE"
    VARIADIC = "VARIADIC"
    WITH = "WITH"

    # Unreserved keywords
    ABORT = "ABORT"
    ABSTRACT = "ABSTRACT"
    ACCESS = "ACCESS"
    AFTER = "AFTER"
    ALIAS = "ALIAS"
    ALL = "ALL"
    ALLOW = "ALLOW"
    ANNOTATION = "ANNOTATION"
    APPLIED = "APPLIED"
    AS = "AS"
    ASC = "ASC"
    ASSIGNMENT = "ASSIGNMENT"
    BEFORE = "BEFORE"
    BLOBAL = "BLOBAL"
    BRANCH = "BRANCH"
    CARDINALITY = "CARDINALITY"
    CAST = "CAST"
    COMMITTED = "COMMITTED"
    CONFIG = "CONFIG"
    CONFLICT = "CONFLICT"
    CONSTRAINT = "CONSTRAINT"
    CUBE = "CUBE"
    CURRENT = "CURRENT"
    DATA = "DATA"
    DATABASE = "DATABASE"
    DDL = "DDL"
    DECLARE = "DECLARE"
    DEFAULT = "DEFAULT"
    DEFERRABLE = "DEFERRABLE"
    DEFERRED = "DEFERRED"
    DELEGATED = "DELEGATED"
    DENY = "DENY"
    DESC = "DESC"
    EACH = "EACH"
    EMPTY = "EMPTY"
    EXCEPT = "EXCEPT"
    EXPRESSION = "EXPRESSION"
    EXTENSION = "EXTENSION"
    FINAL = "FINAL"
    FIRST = "FIRST"
    FORCE = "FORCE"
    FROM = "FROM"
    FUNCTION = "FUNCTION"
    FUTURE = "FUTURE"
    IMPLICIT = "IMPLICIT"
    INDEX = "INDEX"
    INFIX = "INFIX"
    INHERITABLE = "INHERITABLE"
    INSTANCE = "INSTANCE"
    INTERSECT = "INTERSECT"
    INTO = "INTO"
    ISOLATION = "ISOLATION"
    JSON = "JSON"
    LAST = "LAST"
    LINK = "LINK"
    MIGRATION = "MIGRATION"
    MULTI = "MULTI"
    NAMED = "NAMED"
    OBJECT = "OBJECT"
    OF = "OF"
    ONLY = "ONLY"
    ONTO = "ONTO"
    OPERATOR = "OPERATOR"
    OPTIONALITY = "OPTIONALITY"
    ORDER = "ORDER"
    ORPHAN = "ORPHAN"
    OVERLOADED = "OVERLOADED"
    OWNED = "OWNED"
    PACKAGE = "PACKAGE"
    POLICY = "POLICY"
    POPULATE = "POPULATE"
    POSTFIX = "POSTFIX"
    PREFIX = "PREFIX"
    PROPERTY = "PROPERTY"
    PROPOSED = "PROPOSED"
    PSEUDO = "PSEUDO"
    READ = "READ"
    REJECT = "REJECT"
    RELEASE = "RELEASE"
    RENAME = "RENAME"
    REPEATABLE = "REPEATABLE"
    REQUIRED = "REQUIRED"
    RESET = "RESET"
    RESTRICT = "RESTRICT"
    REWRITE = "REWRITE"
    ROLE = "ROLE"
    ROLES = "ROLES"
    ROLLUP = "ROLLUP"
    SAVEPOINT = "SAVEPOINT"
    SCALAR = "SCALAR"
    SCHEMA = "SCHEMA"
    SDL = "SDL"
    SERIALIZABLE = "SERIALIZABLE"
    SESSION = "SESSION"
    SOURCE = "SOURCE"
    SUPERUSER = "SUPERUSER"
    SYSTEM = "SYSTEM"
    TARGET = "TARGET"
    TEMPLATE = "TEMPLATE"
    TERNARY = "TERNARY"
    TEXT = "TEXT"
    THEN = "THEN"
    TO = "TO"
    TRANSACTION = "TRANSACTION"
    TRIGGER = "TRIGGER"
    TYPE = "TYPE"
    UNION = "UNION"
    UNLESS = "UNLESS"
    USING = "USING"
    VERBOSE = "VERBOSE"
    VERSION = "VERSION"
    VIEW = "VIEW"
    WRITE = "WRITE"


class Assoc(enum.Enum):
    LEFT = enum.auto()
    RIGHT = enum.auto()
    NONASSOC = enum.auto()


class Operation(enum.Enum):
    TYPECAST = enum.auto()
    PARENEXPR = enum.auto()


PRECEDENCE: dict[
    Token | tuple[Token, int] | Operation, tuple[int, Assoc]
] = {
    Token.UNION: (0, Assoc.LEFT),
    Token.EXCEPT: (0, Assoc.LEFT),
    Token.INTERSECT: (1, Assoc.LEFT),
    Token.IF: (2, Assoc.RIGHT),
    Token.ELSE: (2, Assoc.RIGHT),
    Token.OR: (3, Assoc.LEFT),
    Token.AND: (4, Assoc.LEFT),
    Token.NOT: (5, Assoc.RIGHT),
    Token.LIKE: (6, Assoc.NONASSOC),
    Token.ILIKE: (6, Assoc.NONASSOC),
    Token.IN: (7, Assoc.NONASSOC),
    Token.IDENT: (8, Assoc.NONASSOC),
    Token.DISTINCTFROM: (9, Assoc.NONASSOC),
    Token.EQUALS: (9, Assoc.NONASSOC),
    Token.GREATEREQ: (9, Assoc.NONASSOC),
    Token.LANGBRACKET: (9, Assoc.NONASSOC),
    Token.LESSEQ: (9, Assoc.NONASSOC),
    Token.NOTDISTINCTFROM: (9, Assoc.NONASSOC),
    Token.NOTEQ: (9, Assoc.NONASSOC),
    Token.RANGBRACKET: (9, Assoc.NONASSOC),
    Token.IS: (10, Assoc.NONASSOC),
    Token.PLUS: (11, Assoc.LEFT),
    Token.MINUS: (11, Assoc.LEFT),
    Token.DOUBLEPLUS: (11, Assoc.LEFT),
    Token.STAR: (12, Assoc.LEFT),
    Token.SLASH: (12, Assoc.LEFT),
    Token.DOUBLESLASH: (12, Assoc.LEFT),
    Token.PERCENT: (12, Assoc.LEFT),
    Token.DOUBLEQMARK: (13, Assoc.RIGHT),
    Token.TYPEOF: (14, Assoc.NONASSOC),
    Token.INTROSPECT: (15, Assoc.NONASSOC),
    Token.PIPE: (16, Assoc.LEFT),
    Token.AMPER: (17, Assoc.LEFT),
    (Token.MINUS, 1): (18, Assoc.RIGHT),
    Operation.PARENEXPR: (18, Assoc.NONASSOC),
    Token.EXISTS: (18, Assoc.RIGHT),
    Token.DISTINCT: (18, Assoc.RIGHT),
    Token.CIRCUMFLEX: (19, Assoc.RIGHT),
    Operation.TYPECAST: (20, Assoc.RIGHT),
    Token.LBRACE: (21, Assoc.LEFT),
    Token.RBRACE: (21, Assoc.LEFT),
    Token.LBRACKET: (22, Assoc.LEFT),
    Token.RBRACKET: (22, Assoc.LEFT),
    Token.LPAREN: (23, Assoc.LEFT),
    Token.RPAREN: (23, Assoc.LEFT),
    Token.DOT: (24, Assoc.LEFT),
    Token.DOTBW: (24, Assoc.LEFT),
    Token.DETACHED: (24, Assoc.RIGHT),
    Token.GLOBAL: (25, Assoc.RIGHT),
    Token.DOUBLECOLON: (26, Assoc.LEFT),
    Token.AT: (27, Assoc.LEFT),
    Token.REQUIRED: (28, Assoc.RIGHT),
    Token.OPTIONAL: (28, Assoc.RIGHT),
    Token.MULTI: (28, Assoc.RIGHT),
    Token.SINGLE: (28, Assoc.RIGHT),
}
