# SPDX-PackageName: gel-python
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright Gel Data Inc. and the contributors.

"""EdgeQL Query Builder"""

from __future__ import annotations

from ._abstract import (
    AbstractDescriptor,
    AbstractFieldDescriptor,
    Expr,
    PathPrefix,
    PathTypeIntersectionPrefix,
    Scope,
    ScopeContext,
    Stmt,
)

from ._expressions import (
    BinaryOp,
    BoolLiteral,
    BytesLiteral,
    CastOp,
    DecimalLiteral,
    DeleteStmt,
    Direction,
    EmptyDirection,
    ExprPlaceholder,
    Filter,
    FloatLiteral,
    ForStmt,
    FuncCall,
    Global,
    IndexOp,
    InfixOp,
    IntLiteral,
    Limit,
    Literal,
    ObjectWhenType,
    Offset,
    OrderBy,
    OrderByElem,
    OrderByExpr,
    OrderDirection,
    OrderEmptyDirection,
    Path,
    SchemaSet,
    SelectStmt,
    SetLiteral,
    Shape,
    ShapeElement,
    ShapeOp,
    Splat,
    StringLiteral,
    UnaryOp,
    UpdateStmt,
    Variable,
    construct_infix_op_chain,
    empty_set,
    empty_set_if_none,
    expr_uses_auto_splat,
    get_object_type_splat,
    toplevel_edgeql,
)

from ._generics import (
    OPERAND_IS_ALIAS,
    AnnotatedGlobal,
    AnnotatedExpr,
    AnnotatedPath,
    AnnotatedVar,
    BaseAlias,
    CheckedBoolOpType,
    CheckedContainsOpType,
    ExprAlias,
    GlobalAlias,
    PathAlias,
    SortAlias,
    VarAlias,
    is_pointer_descriptor,
    get_origin,
)

from ._protocols import (
    ExprClosure,
    ExprCompatible,
    edgeql_qb_expr,
    edgeql,
    exprmethod,
    is_expr_compatible,
)

from ._reflection import (
    GelLinkMetadata,
    GelPointerReflection,
    GelReflectionProto,
    GelSchemaMetadata,
    GelSourceMetadata,
    GelTypeMetadata,
    GelObjectTypeExprMetadata,
    GelObjectTypeMetadata,
)


__all__ = (
    "OPERAND_IS_ALIAS",
    "AbstractDescriptor",
    "AbstractFieldDescriptor",
    "AnnotatedExpr",
    "AnnotatedGlobal",
    "AnnotatedPath",
    "AnnotatedVar",
    "BaseAlias",
    "BinaryOp",
    "BoolLiteral",
    "BytesLiteral",
    "CastOp",
    "CheckedBoolOpType",
    "CheckedContainsOpType",
    "DecimalLiteral",
    "DeleteStmt",
    "Direction",
    "EmptyDirection",
    "Expr",
    "ExprAlias",
    "ExprClosure",
    "ExprCompatible",
    "ExprPlaceholder",
    "Filter",
    "FloatLiteral",
    "ForStmt",
    "FuncCall",
    "GelLinkMetadata",
    "GelObjectTypeExprMetadata",
    "GelObjectTypeMetadata",
    "GelPointerReflection",
    "GelReflectionProto",
    "GelSchemaMetadata",
    "GelSourceMetadata",
    "GelTypeMetadata",
    "Global",
    "GlobalAlias",
    "IndexOp",
    "InfixOp",
    "IntLiteral",
    "Limit",
    "Literal",
    "ObjectWhenType",
    "Offset",
    "OrderBy",
    "OrderByElem",
    "OrderByExpr",
    "OrderDirection",
    "OrderEmptyDirection",
    "Path",
    "PathAlias",
    "PathPrefix",
    "PathTypeIntersectionPrefix",
    "SchemaSet",
    "Scope",
    "ScopeContext",
    "SelectStmt",
    "SetLiteral",
    "Shape",
    "ShapeElement",
    "ShapeOp",
    "SortAlias",
    "Splat",
    "Stmt",
    "StringLiteral",
    "UnaryOp",
    "UpdateStmt",
    "VarAlias",
    "Variable",
    "construct_infix_op_chain",
    "edgeql",
    "edgeql_qb_expr",
    "empty_set",
    "empty_set_if_none",
    "expr_uses_auto_splat",
    "exprmethod",
    "get_object_type_splat",
    "get_origin",
    "is_expr_compatible",
    "is_pointer_descriptor",
    "toplevel_edgeql",
)
