# SPDX-PackageName: gel-python
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright Gel Data Inc. and the contributors.


"""API exported to generated Pydantic-based models."""

from pydantic import (
    PrivateAttr,
    computed_field,
)

from gel._internal._deferred_import import DeferredImport
from gel._internal._edgeql import Cardinality, PointerKind
from gel._internal._lazyprop import LazyClassProperty
from gel._internal._schemapath import ParametricTypeName, SchemaPath, TypeName
from gel._internal._typing_dispatch import dispatch_overload
from gel._internal._utils import UnspecifiedType, Unspecified
from gel._internal._xmethod import classonlymethod

from gel._internal._qb import (
    OPERAND_IS_ALIAS,
    AnnotatedExpr,
    BaseAlias,
    BigIntLiteral,
    BoolLiteral,
    BytesLiteral,
    CastOp,
    DecimalLiteral,
    EmptyDirection,
    Direction,
    FloatLiteral,
    GelLinkMetadata,
    GelObjectTypeMetadata,
    GelPointerReflection,
    GelSchemaMetadata,
    GelTypeMetadata,
    ExprClosure,
    ExprCompatible,
    IndexOp,
    InfixOp,
    IntLiteral,
    FuncCall,
    ObjectWhenType,
    PathAlias,
    SetLiteral,
    StringLiteral,
    UnaryOp,
    construct_infix_op_chain,
)

from gel._internal._qbmodel._abstract import (
    DEFAULT_VALUE,
    AnyEnum,
    AnyEnumMeta,
    AnyNamedTuple,
    AnyNamedTupleMeta,
    AnyTuple,
    ArrayMeta,
    DateImpl,
    DateTimeImpl,
    DateTimeLike,
    DefaultValue,
    GelLinkModelDescriptor,
    GelScalarType,
    GelType,
    GelTypeMeta,
    Global,
    JSONImpl,
    MultiRangeMeta,
    TimeDeltaImpl,
    TimeImpl,
    TupleMeta,
    PyConstType,
    PyTypeScalarConstraint,
    RangeMeta,
    UUIDImpl,
    empty_set_if_none,
)

from gel._internal._qbmodel._pydantic import (
    Array,
    GelLinkModel,
    GelModel,
    GelModelMeta,
    GelObjectModel,
    IdProperty,
    LinkClassNamespace,
    ComputedLinkWithProps,
    ComputedMultiLink,
    ComputedMultiLinkWithProps,
    ComputedMultiProperty,
    ComputedProperty,
    ComputedLink,
    RequiredMultiLink,
    RequiredMultiLinkWithProps,
    MultiProperty,
    MultiRange,
    OptionalLink,
    OptionalLinkWithProps,
    OptionalMultiLink,
    OptionalMultiLinkWithProps,
    OptionalProperty,
    OptionalComputedLink,
    OptionalComputedLinkWithProps,
    OptionalComputedProperty,
    ProxyModel,
    Property,
    RequiredLink,
    RequiredLinkWithProps,
    PyTypeScalar,
    Range,
    Tuple,
)

__all__ = (
    "DEFAULT_VALUE",
    "OPERAND_IS_ALIAS",
    "AnnotatedExpr",
    "AnyEnum",
    "AnyEnumMeta",
    "AnyNamedTuple",
    "AnyNamedTupleMeta",
    "AnyTuple",
    "Array",
    "ArrayMeta",
    "BaseAlias",
    "BigIntLiteral",
    "BoolLiteral",
    "BytesLiteral",
    "Cardinality",
    "CastOp",
    "ComputedLink",
    "ComputedLinkWithProps",
    "ComputedMultiLink",
    "ComputedMultiLinkWithProps",
    "ComputedMultiProperty",
    "ComputedProperty",
    "DateImpl",
    "DateTimeImpl",
    "DateTimeLike",
    "DecimalLiteral",
    "DefaultValue",
    "DeferredImport",
    "Direction",
    "EmptyDirection",
    "ExprClosure",
    "ExprCompatible",
    "FloatLiteral",
    "FuncCall",
    "GelLinkMetadata",
    "GelLinkModel",
    "GelLinkModelDescriptor",
    "GelModel",
    "GelModelMeta",
    "GelObjectModel",
    "GelObjectTypeMetadata",
    "GelPointerReflection",
    "GelScalarType",
    "GelSchemaMetadata",
    "GelType",
    "GelTypeMeta",
    "GelTypeMetadata",
    "Global",
    "IdProperty",
    "IndexOp",
    "InfixOp",
    "IntLiteral",
    "JSONImpl",
    "LazyClassProperty",
    "LinkClassNamespace",
    "MultiProperty",
    "MultiRange",
    "MultiRangeMeta",
    "ObjectWhenType",
    "OptionalComputedLink",
    "OptionalComputedLinkWithProps",
    "OptionalComputedProperty",
    "OptionalLink",
    "OptionalLinkWithProps",
    "OptionalMultiLink",
    "OptionalMultiLinkWithProps",
    "OptionalProperty",
    "ParametricTypeName",
    "PathAlias",
    "PointerKind",
    "PrivateAttr",
    "Property",
    "ProxyModel",
    "PyConstType",
    "PyTypeScalar",
    "PyTypeScalarConstraint",
    "Range",
    "RangeMeta",
    "RequiredLink",
    "RequiredLinkWithProps",
    "RequiredMultiLink",
    "RequiredMultiLinkWithProps",
    "SchemaPath",
    "SetLiteral",
    "StringLiteral",
    "TimeDeltaImpl",
    "TimeImpl",
    "Tuple",
    "TupleMeta",
    "TypeName",
    "UUIDImpl",
    "UnaryOp",
    "Unspecified",
    "UnspecifiedType",
    "classonlymethod",
    "computed_field",
    "construct_infix_op_chain",
    "dispatch_overload",
    "empty_set_if_none",
)
