# SPDX-PackageName: gel-python
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright Gel Data Inc. and the contributors.


"""API exported to generated Pydantic-based models."""

from pydantic import (
    PrivateAttr,
    computed_field,
)

from gel._internal._edgeql import Cardinality, PointerKind
from gel._internal._lazyprop import LazyClassProperty
from gel._internal._reflection import SchemaPath
from gel._internal._typing_dispatch import dispatch_overload
from gel._internal._utils import UnspecifiedType, Unspecified
from gel._internal._xmethod import classonlymethod

from gel._internal._qb import (
    AnnotatedExpr,
    BaseAlias,
    EmptyDirection,
    Direction,
    GelLinkMetadata,
    GelObjectTypeMetadata,
    GelPointerReflection,
    GelTypeMetadata,
    ExprClosure,
    ExprCompatible,
    IndexOp,
    InfixOp,
    PrefixOp,
    FuncCall,
    PathAlias,
)

from gel._internal._qbmodel._abstract import (
    DEFAULT_VALUE,
    AnyEnum,
    AnyNamedTuple,
    AnyTuple,
    BaseScalar,
    DateImpl,
    DateTimeImpl,
    DateTimeLike,
    DefaultValue,
    GelType,
    GelType_T,
    GelTypeMeta,
    TimeDeltaImpl,
    TimeImpl,
    PyConstType,
    UUIDImpl,
    empty_set_if_none,
)

from gel._internal._qbmodel._pydantic import (
    Array,
    GelLinkModel,
    GelModel,
    GelModelMeta,
    IdProperty,
    LinkClassNamespace,
    LinkPropsDescriptor,
    LinkWithProps,
    ComputedLinkWithProps,
    ComputedMultiLink,
    ComputedMultiLinkWithProps,
    ComputedMultiProperty,
    ComputedProperty,
    MultiLink,
    RequiredMultiLink,
    RequiredMultiLinkWithProps,
    MultiLinkWithProps,
    MultiProperty,
    MultiRange,
    OptionalLink,
    OptionalLinkWithProps,
    OptionalProperty,
    OptionalComputedLink,
    OptionalComputedLinkWithProps,
    OptionalComputedProperty,
    ProxyModel,
    Property,
    PyTypeScalar,
    Range,
    Tuple,
)


__all__ = (
    "DEFAULT_VALUE",
    "AnnotatedExpr",
    "AnyEnum",
    "AnyNamedTuple",
    "AnyTuple",
    "Array",
    "BaseAlias",
    "BaseScalar",
    "Cardinality",
    "ComputedLinkWithProps",
    "ComputedMultiLink",
    "ComputedMultiLinkWithProps",
    "ComputedMultiProperty",
    "ComputedProperty",
    "DateImpl",
    "DateTimeImpl",
    "DateTimeLike",
    "DefaultValue",
    "Direction",
    "EmptyDirection",
    "ExprClosure",
    "ExprCompatible",
    "FuncCall",
    "GelLinkMetadata",
    "GelLinkModel",
    "GelModel",
    "GelModelMeta",
    "GelObjectTypeMetadata",
    "GelPointerReflection",
    "GelType",
    "GelTypeMeta",
    "GelTypeMetadata",
    "GelType_T",
    "IdProperty",
    "IndexOp",
    "InfixOp",
    "LazyClassProperty",
    "LinkClassNamespace",
    "LinkPropsDescriptor",
    "LinkWithProps",
    "MultiLink",
    "MultiLinkWithProps",
    "MultiProperty",
    "MultiRange",
    "OptionalComputedLink",
    "OptionalComputedLinkWithProps",
    "OptionalComputedProperty",
    "OptionalLink",
    "OptionalLinkWithProps",
    "OptionalProperty",
    "PathAlias",
    "PointerKind",
    "PrefixOp",
    "PrivateAttr",
    "Property",
    "ProxyModel",
    "PyConstType",
    "PyTypeScalar",
    "Range",
    "RequiredMultiLink",
    "RequiredMultiLinkWithProps",
    "SchemaPath",
    "TimeDeltaImpl",
    "TimeImpl",
    "Tuple",
    "UUIDImpl",
    "Unspecified",
    "UnspecifiedType",
    "classonlymethod",
    "computed_field",
    "dispatch_overload",
    "empty_set_if_none",
)
